version: 1
accounts:
  - name: alice
    coins:
      - 200000000himitsu
  - name: bob
    coins:
      - 100000000himitsu
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 1000000000himitsu
validators:
  - name: alice
    bonded: 100000000himitsu

genesis:
  app_state:
    staking:
      params:
        bond_denom: "himitsu"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "himitsu"
    crisis:
      constant_fee:
        denom: "himitsu"
    mint:
      params:
        mint_denom: "himitsu"
